export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOAD_TRUE = 'load_true'
export const REGISTER_USER_SUCCESS = 'register_user_success'
export const REGISTER_USER_FAIL = 'register_user_fail'

export const USER_INFO_SUCCESS = 'user_info_success'
export const USER_INFO_FAIL = 'user_info_fail'
